# Site
repository: ozhanozen/ozhanozen.github.io
favicon: images/favicon.svg

# Content configuration version
version: 2

# Personal info
name: Özhan Özen
title: Data Scientist & Robotics Engineer
website: ozhanozen.github.io
email: oezhan.oezen@gmail.com
wemail: oezhan.oezen@sipbb.ch

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ozhanozen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: _ozhanozen_
linkedin_username: ozhan-ozen
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
#googlescholar_username: r3qxU7oAAAAJ

additional_links:
- title: GoogleScholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=dU4vyFAAAAAJ&hl


# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I'm an engineer at the intersection of AI, robotics, and healthcare. During my PhD studies, I worked on the utilization of reinforcement learning in robot-assisted motor 
  skill training and neurorehabilitation. Currently, I am working at the Swiss Battery Technology Center (within the Switzerland Innovation Park Biel/Bienne), 
  developing a robotic system to automatically disassemble EV batteries. 

  I am most interested in: <mark>robotics</mark>, <mark>deep reinforcement learning</mark>, and <mark>human motor learning</mark>.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Data Scientist & Scientific Project Leader
        link: sipbb.ch
        # link_text: boringcompany.com
        sub_title: Switzerland Innovation Park Biel/Bienne Ltd.
        caption: June 2022 - Present
        #quote: >
        #  Using AI and robotics to develop future technology for a more efficient and sustainable future.
        
        description: | # this will include new lines to allow paragraphs
            Using AI and robotics to develop future technology for a more efficient and sustainable future. 
            Currently, developing a robotic system that uses deep reinforcement learning to learn how to automatically disassemble EV batteries.

      - layout: left
        title: Robotics Engineer
        link: preentechnologies.com
        # link_text: boringcompany.com
        sub_title: Preen AG | Zurich, Switzerland
        caption: Jan 2022 - May 2022
        description: | # this will include new lines to allow paragraphs
            Robotic software development.
            Robot & camera calibration.

      - layout: left
        title: PhD Researcher in Biomedical Engineering
        # link_text: boringcompany.com
        sub_title: University of Bern | Switzerland
        caption: Nov 2017 - Oct 2021 
        description: | # this will include new lines to allow paragraphs
            Developing intelligent algorithms that can automatically learn how to modulate robotic assistance for accelerating individuals' motor 
            learning in the context of robotic neurorehabilitation.
      
      - layout: left
        title: Rehabilitation Robotics Intern
        # link_text: boringcompany.com
        sub_title: University of Zurich | Switzerland
        caption: Sep 2016 - Feb 2017
        description: | # this will include new lines to allow paragraphs
            Internship on rehabilitation robotics at the Spinal Cord Injury Center, Balgrist, with a focus on motion control design & development for 
            ARMin exoskeleton rehabilitation robot. 
      
      - layout: left
        title: Robotics Intern
        # link_text: boringcompany.com
        sub_title: Keio University | Tokyo, Japan
        caption: Jun 2014 - Aug 2014
        description: | # this will include new lines to allow paragraphs
            Robotics & motion control systems internship at the Ohnishi Laboratory.

      - layout: left
        title: Robotics Intern
        # link_text: boringcompany.com
        sub_title: ABB | Istanbul, Turkey
        caption: Jun 2013 - Aug 2013
        description: | # this will include new lines to allow paragraphs
            Industrial robot programming.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PhD in Biomedical Engineering
        sub_title: University of Bern | Switzerland
        caption: 2017 - 2021
        description: | # this will include new lines to allow paragraphs
          PhD thesis at the MLN Lab: "Intelligence, Adaptation and Automation of Robotic Training for Motor Learning and Neurorehabilitation."
      
      - layout: left
        title: MSc in Robotics, Systems & Control
        caption: 2015 - 2017
        sub_title: ETH Zurich | Switzerland
        description: | # this will include new lines to allow paragraphs
          MSc thesis at the Sensory-Motor System Lab: “Human Arm Joint Torque Estimation with Rehabilitation Robots.”

      - layout: left
        title: BSc in Mechatronics Engineering
        caption: 2010 - 2015
        sub_title: Sabanci University | Istanbul, Turkey
        description: | # this will include new lines to allow paragraphs
          BSc Thesis: “Stewart Manipulator Design and Control for Surgery.”
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my professional interests, some of my other interests and hobbies are:
      - Wind-/Kitesurfing
      - Squash
      - Lindyhop
    

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: ozhanozen/ozhanozen.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag


exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
